### PR TITLE
Winapi update

### PR DESCRIPTION
**Pull request by Dushistov**
Dependencies update to remove last dependency from winapi 0.2.x in my code.

### CODE REVIEW

**Comment by Dushistov** [comment]
ping @jeandudey

**Comment by jeandudey** [comment]
Thanks for the contribution :-) :+1:

**Comment by jeandudey** [comment]
Tomorrow by the morning (quite late here) I'll upload the new version as I'm not on Windows right now.

**Comment by Dushistov** [comment]
> Tomorrow by the morning (quite late here) I'll upload the new version as I'm not on Windows right now.

@jeandudey , any updates?

**Pull request merged**
